TEAMS = [
    "Calojira",
    "Mega Caca",
    "Ultra Commit",
    "Rammchtouille",
    "Les dandys pimpants",
    "Jean-Michel Barre (de fer)",
    "Dix Artwork (Die Antwoord)",
    "Maladie VTC (Therapie Taxi)",
    "Les ados roux (BB brunes)",
    "Lady boy (Lady gaga)",
    "Maître Git (Maitre gims)",
    "MC Lunaar",
    "Raft Drunk",
    "Supreme ULM",
    "Les pleurs de l'armée bleue",
    "Petit corps en forme",
    "Jacques Dufond",
    "Christine and the kouign amann",
    "Simon & gare de l'est",
    "Dildo (Dido)",
    "Michel Poliakov",
    "Pascal AuBistrot",
    "White nose bean",
    "Kaboul ruins (Tokio hotel)",
    "Gorillettes (de canard)",
    "Shallow Yellow (deep purple)",
    "Gooda (booba)",
    "Angnome (Anggun)",
    "9 months to Uranus",
    "Vim'K (Keen'V)",
    "Marvin Baille",
    "3 centimeters screws",
    "Red Night (green day)",
    "Forty two passengers (21 pilots)",
    "Two dictatures (One republic)",
    "Hotstop (Coldplay)",
    "Emmy Nem",
    "My natural divorce (My chemical romance)",
    "Drill Brothers (Scissors sisters)",
    "The poopy bananas (the bloody beetroots)",
    "Julien Obscur",
    "Les astiqueurs de dolmen (Les ramoneurs de menhirs)",
    "Tête de corsair (Coeur de pirate)",
    "(Francis Lalanne) Francis Lasagnes",
    "(Desirless) Hateful",
    "Axelle RAID",
    "Jean-Michel .jar",
]
